# Generated by Django 3.2.5 on 2021-07-30 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='time_tamp',
        ),
        migrations.AddField(
            model_name='postview',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
